language: java
sudo: false
install: true

jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
script:
  - ./travis.sh
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $BUILD_DEPLOY_GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master